apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
data:
  #Mail Settings
  MAIL_USER: 'NjcyMDIxMjMxQHN0dWRlbnQudWtzdy5lZHU='
  MAIL_PASSWORD: 'enhtaiBheHNvIG51ZmsgbWxnaw=='

  #Database with supabase settings
  DATABASE_URL: 'cG9zdGdyZXNxbDovL3Bvc3RncmVzLmxxa251a3plYmVzcGJnZ25vd2RoOmlwWUo4dFQyT09ucHpVZ2RAYXdzLTAtYXAtc291dGhlYXN0LTEucG9vbGVyLnN1cGFiYXNlLmNvbTo2NTQzL3Bvc3RncmVzP3BnYm91bmNlcj10cnVlJmNvbm5lY3Rpb25fbGltaXQ9MQ=='
  DIRECT_URL: 'cG9zdGdyZXNxbDovL3Bvc3RncmVzLmxxa251a3plYmVzcGJnZ25vd2RoOmlwWUo4dFQyT09ucHpVZ2RAYXdzLTAtYXAtc291dGhlYXN0LTEucG9vbGVyLnN1cGFiYXNlLmNvbTo1NDMyL3Bvc3RncmVz'

  SUPABASE_KEY: 'ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW14eGEyNTFhM3BsWW1WemNHSm5aMjV2ZDJSb0lpd2ljbTlzWlNJNkltRnViMjRpTENKcFlYUWlPakUzTWpjMk56STJNallzSW1WNGNDSTZNakEwTXpJME9EWXlObjAuVGNOZWZTUnd0YVlCNy1PcjVHMGdNOFZRVDN4ZTlLRnNRV0dPVko0OG9WZw=='
  SUPABASE_URL: 'aHR0cHM6Ly9scWtudWt6ZWJlc3BiZ2dub3dkaC5zdXBhYmFzZS5jbw=='
  SUPABASE_BUCKET: 'c2tpbGluc19zdG9yYWdl'

  AUTH_JWT_SECRET: 'JDJ5JDEwJE5vaEpGYVZ3a1RlOTdtbDNZbTdCRC5CQTlkY0tkY3FYTmFjTzU4WUpUV1FFSGIwM0puVmNp'
  AUTH_REFRESH_SECRET: 'JDJ5JDEwJFY4U0pmdVhlQ3ByRElRaFFPUkYwZy4xdmpDTEhHc2JIUGk5VDNuSXJneURNZFFOTUcxS1N5'
  AUTH_FORGOT_SECRET: 'JDJ5JDEwJFNGZTQzUFZXMWtuYWt2bWY4b0ZFc3VZSXRYTWdUNWQubkJzUC42L01Oc0tqaDRKU2pCT1FX'
  AUTH_CONFIRM_EMAIL_SECRET: 'JDJ5JDEwJDFZUE5TZjRyYm5ZcURHQm5QUm9KUHVaYk1tbTl0V1VIMnpSS3E3OS5UZmpoeXh2Y0NiN3lD'
